theme: jekyll-theme-cayman
title: Topics analysis of movies and TV series
description: This project goal is to show which are the most common topics amongst movies and TV series and how they evolved over the years.